### PR TITLE
Bugfixes and suggested updates

### PR DESCRIPTION
**Pull request by mm-gmbd**
Comments embedded in edited files with //MMCOMMENT

imp-deploy.js
- [SUGGESTED] removed "devices" from list of config.init() parameters

imp-devices.js
- [SUGGESTED] added --save option to save list of devices to local
  configuration
- [BUGFIX] If any values in filtered devices that are being pushed into
  Table (id, name, model_id, powerstate) are null, they are replaced with
  string "null". This prevents code from breaking on Table.toString().
  Comments are embedded for testing, but can be removed for final merge.

imp-init.js
- [SUGGESTED] Added several options
- [SUGGESTED](Possibly a bugfix?) If model was not found, and user specified that they wanted to use that model name as a new model, the model is now created. Before, if the user said they wanted to use that model, the model would never be created.

imp-migrate.js [NEW]
- Added to facilitate moving device/agent code from development-->production accounts.

imp.js
- Added migrate to list of options.

### CODE REVIEW

**Comment by mm-gmbd** [comment]
I had been making commits on my account, forgetting that they were pushed to the pull request as well. I have updated the list of details above to account for the additional suggestions. Please let me know if I can clarify any suggestions/fixes.

**Comment by cat-haines** [comment]
I've been on vacation and sick for the past couple weeks.. but I'm finally getting around to looking at this :)

**Comment by mm-gmbd** [comment]
Sorry to hear you've been sick! Sounds like no fun :sob: 

When you get around to the request, hopefully you'll find the changes worthwhile. I'd prefer using your version of the cli rather than my forked version :smile:

**Comment by cat-haines** [comment]
Not certain I understand why you added the --save flag to devices.. can you explain the use case?

**Comment by mm-gmbd** [comment]
Hmm, once upon a time I had a reason for adding it, but I can't seem to remember it, and looking back it isn't used anywhere, so I'm fine with omitting that.

I think maybe it was just so there one could opt to have a local record of devices associated with the account, but that doesn't seem very imperative (at least, not at this point).

**Comment by cat-haines** [comment]
I can see something like that being useful (a future improvement is having a local cache, and only requesting devices/models when an error occurs, or there's a cache miss).

I'm going to omit that part in this PR.. but I think it could definitely fit into a future enhancement at some point.

**Comment by cat-haines** [comment]
This looks good - I've updated the option names for init:
- overview -> force
- keepDeviceCode, keepAgentCode, keepBoth -> -k, --keep [agent | device]

I like what the migrate command allows you to do.. but I'm not certain a separate command for it is the right way to go about things. I'll include it in this PR, but I want to see about working towards something a bit more robust. 

I'm thinking about an "environment" command that would act somewhat similar to Git's remote command. You could add, remove and list environments (which would essentially be a Build API Key, plus the modelId and device list for the model associated to the account).

We could add an environment option to most of the commands to use the specified 'environment'/Build API Key.. this would let you simply run the following command to push your code to your prod account:

`imp deploy -e prod`

**Comment by mm-gmbd** [comment]
Ah, agreed - an "environment" option would almost assuredly be the way to go. Thanks for merging!

**Pull request merged**
